# Generated by Django 5.2.6 on 2025-09-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurants',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='ratings',
            new_name='rating',
        ),
    ]
